title = "Bamboo Blog"
base_url = "http://localhost:3000"
description = "Thoughts on software engineering, compression algorithms, and building the new internet."
author = "Richard Hendricks"
language = "en"

[extra]
github = "https://github.com/richardhendricks"
twitter = "@richardhendricks"
