title = "Richard Hendricks"
base_url = "http://localhost:3000"
description = "CEO & Founder at Pied Piper"
author = "Richard Hendricks"
language = "en"

[extra]
tagline = "CEO & Founder at Pied Piper"
email = "richard@piedpiper.com"
github = "https://github.com"
linkedin = "https://linkedin.com"
